[build]
  publish = "."  # Publikacija iz trenutnog direktorijuma
  command = ""  # Ako nemaš build alat, ovo može biti prazno

[dev]
  command = "live-server"  # Ako koristiš live-server za lokalni razvoj
  port = 8080
